- name: "Running kubadm command"
  command: kubeadm init --pod-network-cidr=10.240.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  args:
          creates: /etc/kubernetes/admin.conf
  notify: startflannel
  register: x

- name: " Printing Token"
  command: "kubeadm token create --print-join-command"
  register: token
  when: x.changed is true

- name: " Storing to local storage"
  copy:
          content: "{{ token.stdout }}"
          dest: /ansi/k8s_final/MultiNodeCluster/files/token.txt
  delegate_to: localhost

- name: "Create .kube Directory"
  file:
          dest: ~/.kube
          state: directory

- name: send to .kube/config
  copy:
          src: /etc/kubernetes/admin.conf
          dest: $HOME/.kube/config
          remote_src: yes
          owner: "{{ ansible_effective_user_id }}"
          group: "{{ ansible_effective_group_id }}"
